---
galaxy_info:
  role_name: build_cleanup
  namespace: cowdogmoo
  author: CowDogMoo
  description: General-purpose, parameterized cleanup role for build artifact minimization
  company: CowDogMoo

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - cleanup
    - build
    - container
    - docker
    - image
    - optimization
    - sizereduction
    - packer
    - ci
    - cd

dependencies: []
