$ANSIBLE_VAULT;1.1;AES256
33653765363664663064656330306564616164363562626530303162353834373963326233336165
3064633766303133393938656263386535646430613630650a666337623766633037346331656130
30386166623465613436393564363161636334303733313361333531363233363064626230333231
3963353461323364380a313465623334653264356337323535393733313334613639626335623432
34373366636438633264333237326638653634333536653031353336323536396661373963353264
64333530663430343065343734626666613537633133363037666166643036353233323830396339
61363266353066303562613133323962303262396362333632383164623932663161656161623664
34383232393761383361373466616666396537303430663131626461613965626363363233343666
61616564663631643331626233626362363363393361616662623131323539323731303630353162
32363462363138656139323330333032386261616465343961386564316639393135613463626539
38353361363765343061633638363262636634366133346164396466613338306536616461613038
65333264656231373138
