---
- name: Destroy
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy molecule instance(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
      register: fabric_destroy_server
      loop: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: fabric_destroy_docker_jobs
      until: fabric_destroy_docker_jobs.finished
      retries: 300
      loop: "{{ fabric_destroy_server.results }}"
